language: java
jdk:
  - oraclejdk8
dist: trusty
before_install:
  - sudo apt-get install default-jdk ant python2.7 git
  - git clone https://github.com/facebook/buck.git
  - cd buck
  - ant
  - cd ../
script:
  - ./buck/bin/buck test
  - ./buck/bin/buck build :buckaroo-cli
sudo: required
