sudo: required

language: java

services:
  - docker

before_install:
  - docker pull njlr/buck:v2
  - docker run -itd --name build njlr/buck:v2
  - docker exec build git clone https://github.com/LoopPerfect/buckaroo.git

script:
  - docker exec build /bin/bash -c 'cd /buckaroo && buck test'
  - docker exec build /bin/bash -c 'cd /buckaroo && buck build :buckaroo'
  - docker exec build /bin/bash -c 'cd /buckaroo && buck build :buckaroo-cli'
  - docker exec build /bin/bash -c 'java -jar /buckaroo/buck-out/gen/buckaroo-cli.jar version'
