language: csharp
solution: buckaroo.sln
mono: none
dotnet: 2.1
addons:
  apt:
    packages:
    - hello
  homebrew:
    packages:
    - hello
os:
  - linux
  - osx
script: 
  - dotnet build ./buckaroo
  - dotnet build ./buckaroo-cli
  - dotnet test ./buckaroo-tests
