sudo: required

language: java

services:
  - docker

before_install:
  - docker pull prelegalwonder/buck-builder:latest
  - docker run -itd --name build prelegalwonder/buck-builder
  - docker exec build git clone https://github.com/LoopPerfect/buckaroo.git

script:
  - docker exec build cd /root/buckaroo && buck test
  - docker exec build cd /root/buckaroo && buck build :buckaroo
  - docker exec build cd /root/buckaroo && buck run :buckaroo-cli version
