dist: trusty
language: generic

before_install:
  # Install Linuxbrew
  - test -d $HOME/.linuxbrew/bin || git clone https://github.com/Linuxbrew/brew.git $HOME/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$PATH"
  - echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - brew --version
  # Install Buck
  - brew tap facebook/fb
  - brew install buck
  - buck --version

script:
  - buck build :buckaroo
  - buck test :buckaroo-unit
  - buck run :buckaroo-cli

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.linuxbrew/
