language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get install default-jdk ant python2.7 git
  - git clone https://github.com/facebook/buck.git
  - cd buck
  - ant
script: ./bin/buck build :buckaroo-cli
