language: csharp
solution: buckaroo.sln
mono: none
dotnet: 2.1.500
addons:
  apt:
    packages:
    - hello
    - libcurl-dev
  homebrew:
    packages:
    - hello
os:
  - linux
  - osx
script: 
  - dotnet build ./buckaroo
  - dotnet build ./buckaroo-cli
  - dotnet test ./buckaroo-tests
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ./warp-bundle-macos.sh       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./warp-bundle-linux.sh       ; fi
