os: Visual Studio 2015

version: '{build}'

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: choco install buck -y -f -i
  - cmd: refreshenv
  - cmd: python --version
  - cmd: java -version
  - cmd: ant -version
  - cmd: buck --version

# Disable automatic builds by MSBuild
build: off

build_script:
  - "buck build :buckaroo"
  - "buck build :buckaroo-cli"
  - "buck build :buckaroo-unit"
  - "buck build :buckaroo-integration"

test_script:
  - "buck test :buckaroo-unit"

artifacts:
  - path: buck-out\gen\buckaroo-cli.jar
