os: Visual Studio 2015

version: '{build}'

environment:
  BUCK_EXTRA_JAVA_ARGS: "-Djna.nosys=true"
  JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: choco install wget -y --no-progress
  - ps: refreshenv
  - ps: wget "https://github.com/njlr/choco-buck/releases/download/2017.05.31.01/buck.2017.05.31.01.nupkg" -OutFile buck.2017.05.31.01.nupkg
  - ps: choco install buck -s ".;chocolatey" -y --no-progress
  - ps: refreshenv
  - ps: choco list --localonly
  - ps: buck --version

# Disable automatic builds by MSBuild
build: off

build_script:
  - buck build :buckaroo
  - buck build :buckaroo-cli
  - buck build :buckaroo-unit
  - buck build :buckaroo-integration

test_script:
  - buck test :buckaroo-unit

artifacts:
  - path: buck-out\gen\buckaroo-cli.jar
    name: buckaroo-cli.jar

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\buck -> appveyor.yml
