version: '1.0.{build}'
image: Visual Studio 2017
before_build:
  - ps: dotnet --version
build_script:
  - ps: dotnet build ./buckaroo
  - ps: dotnet build ./buckaroo-cli
clone_depth: 1
test_script:
  - ps: dotnet test ./buckaroo-tests
